desenvolvimento/src/ubervents/PROJETO01/PROJETO01/Models/ErrorViewModel.cs
using System;

namespace PROJETO01.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

desenvolvimento/src/ubervents/PROJETO01/PROJETO01/Controllers/CidadeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using PROJETO01.Dados.EntityFramework;
using PROJETO01.Modelos;

namespace PROJETO01.Controllers
{
    public class CidadeController : Controller
    {
        public IActionResult Adicionar()
        {
            var db = new Contexto();
            ViewBag.Estados = db.Estado.ToList();
            return View();
        }

        [HttpPost]
        public IActionResult AdicionarConfirmacao(Cidade cidade)
        {
            return RedirectToAction("Listar");
        }
    }
}

desenvolvimento/src/ubervents/PROJETO01/PROJETO01/Controllers/EstadoController.cs
using Microsoft.AspNetCore.Mvc;
using PROJETO01.Dados.EntityFramework;
using PROJETO01.Modelos;
using PROJETO01.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace PROJETO01.Controllers
{
    public class EstadoController : Controller
    {
        public IActionResult Index(string uf, string estado)
        {
            var objeto = new Estado();
            objeto.UF = uf;
            objeto.Nome = estado;

            return View(objeto);
        }

        [HttpGet]
        public IActionResult Adicionar()
        {
            return View();
        }

        public IActionResult AdicionarConfirmacao(Estado estado)
        {
            var db = new Contexto();

            var obj = db.Estado.FirstOrDefault(f => f.UF == estado.UF);

            if (obj == null)
            {
                db.Estado.Add(estado);
            }
            else
            {
                obj.Nome = estado.Nome;
                db.Estado.Update(obj);
            }
            
            db.SaveChanges();

            return RedirectToAction("Listar");
        }

        [HttpGet]
        public IActionResult Editar(string uf)
        {
            var db = new Contexto();
            var estado = db.Estado.First(item => item.UF == uf);
            return View("Adicionar", estado);
        }

        public IActionResult Listar() {

            //SELECT * FROM Estado
            var listaDeEstados = new Contexto().Estado.ToList();

            return View(listaDeEstados);
        }

        public IActionResult Excluir(string uf)
        {
            var db = new Contexto();
            var estado = db.Estado.First(f => f.UF == uf);
            db.Estado.Remove(estado);
            db.SaveChanges();

            return RedirectToAction("Listar");
        }
    }
}

desenvolvimento/src/ubervents/PROJETO01/PROJETO01/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using PROJETO01.Models;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace PROJETO01.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index(int disciplinaId, string nome)
        {

            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

desenvolvimento/src/ubervents/PROJETO01/PROJETO01/Views/Cidade/Adicionar.cshtml
@model PROJETO01.Modelos.Cidade

    <form asp-controller="Cidade" asp-action="AdicionarConfirmacao" method="post">

        <div class="mb-3">
            <label for="CidadeID" class="form-label">ID:</label>
            <input asp-for="CidadeID" type="text" class="form-control" placeholder="Digite o ID da cidade" />
        </div>

        <div class="mb-3">
            <label for="Nome" class="form-label">Nome:</label>
            <input asp-for="Nome" type="text" class="form-control" placeholder="Digite o nome da cidade." />
        </div>

        <div class="mb-3">
            <label for="UF" class="form-label">Estado:</label>
            @Html.DropDownListFor(
                    item => item.UF, 
                    new SelectList(ViewBag.Estados, "UF", "Nome"),
                    "-- Selecione --",
                    new { @class = "form-control" }
                )
        </div>

        <hr />

        <a href="#" class="btn btn-secondary" onclick="javascript:history.back()">
            VOLTAR
        </a>

        <button type="submit" class="btn btn-success float-right">
            SALVAR
        </button>
    </form>

desenvolvimento/src/ubervents/PROJETO01/PROJETO01/Views/Estado/Adicionar.cshtml
@model PROJETO01.Modelos.Estado

    <form asp-controller="Estado" asp-action="AdicionarConfirmacao" method="post">
        <div class="mb-3">
            <label for="UF" class="form-label">UF:</label>
            <input asp-for="UF" type="text" class="form-control" placeholder="Digite o UF do estado" />
        </div>
        <div class="mb-3">
            <label for="Nome" class="form-label">Nome:</label>
            <input asp-for="Nome" type="text" class="form-control" placeholder="Digite o nome do estado" />
        </div>

        <hr />

        <a href="#" class="btn btn-secondary" onclick="javascript:history.back()">
            VOLTAR
        </a>

        <button type="submit" class="btn btn-success float-right">
            SALVAR
        </button>

    </form>

desenvolvimento/src/ubervents/PROJETO01/PROJETO01/Views/Estado/Index.cshtml
@model PROJETO01.Modelos.Estado

<h1>
    @Model.UF
</h1>

<h4>
    @Model.Nome
</h4>


    <div class="alert alert-warning">
        OOOHH NOO.
    </div>


<input type="text" value="@Model.UF" class="form-control" />
<br />
<input type="text" value="@Model.Nome" />

<br /><br />
<button class="btn btn-block btn-success">
    SUCESSO!
</button>

desenvolvimento/src/ubervents/PROJETO01/PROJETO01/Views/Estado/Listar.cshtml
@model List<PROJETO01.Modelos.Estado>

<h3>
    CADASTRO DE ESTADOS 
    <a class="btn btn-sm btn-primary float-right" href="/Estado/Adicionar">
        + ADICIONAR
    </a>
</h3>

<table class="table table-hover ">
    <thead>
        <tr>
            <th>UF</th>
            <th>Nome</th>
            <th>Ações</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>@item.UF</td>
                <td>@item.Nome</td>
                <td>
                    <a href="/Estado/Editar?uf=@item.UF" class="btn btn-sm btn-warning">
                        Editar
                    </a>
                    <a href="/Estado/Excluir?uf=@item.UF" class="btn btn-sm btn-danger">
                        Excluir
                    </a>
                </td>
            </tr>
        }
    </tbody>
</table>

desenvolvimento/src/ubervents/PROJETO01/PROJETO01/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<h1>
    @ViewBag.Disciplina - @ViewBag.Nome
</h1>

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

desenvolvimento/src/ubervents/PROJETO01/PROJETO01/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PROJETO01</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">PROJETO01</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Estado" asp-action="Listar">Estados</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Cidade" asp-action="Listar">Cidades</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - PROJETO01 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>